### ISSUE TITLE
Assumes prior installation of cbindgen

### ISSUE THREAD

**Issue by JJTech0130** [jkcoxson/em_proxy#1]
Currently, `cbindgen` is not a dependency, so the proper header files will not be generated unless you run `cargo install cbindgen` first. `cbindgen` should be added to `Cargo.toml`

**Comment by jkcoxson** [comment]
That’s not how that works. Cbindgen is not a dependency crate, it’s a binary crate. Adding it to the cargo.toml will not do anything at best, breaking stuff at worst.

**Comment by JJTech0130** [comment]
Wait, so then how do you make sure it's installed for use in `build.rs`?

**Comment by jkcoxson** [comment]
The build script doesn’t check, it silently fails.

**Comment by JJTech0130** [comment]
Yea, so I want to have it be automatically installed, or at least fail with a warning.

**Comment by JJTech0130** [comment]
Shouldn't it be added to `build-dependencies`?
```toml
[build-dependencies]
cc = "1.0"
```
from https://doc.rust-lang.org/cargo/reference/build-script-examples.html

**Comment by jkcoxson** [comment]
Adding it to the dependencies will build it as a library and link it with the target

**Comment by JJTech0130** [comment]
Also, rather then using the CLI, wouldn't it be better to do it like this?
https://github.com/eqrion/cbindgen/blob/master/docs.md#buildrs

**Comment by JJTech0130** [comment]
> Adding it to the dependencies will build it as a library and link it with the target

But not *build* dependencies to the best of my knowledge. It's explicitly designed for this case, right? The cbindgen docs above even recommend it? Unless I'm missing something

**Comment by jkcoxson** [comment]
If you use the build.rs you listed in the readme, then yes build-dependencies would be correct. If we were calling it as CLI like what it does now, then slapping it there wouldn't work because it doesn't install it globally where PATH can find it (if it even builds the binary, which I'm pretty sure it doesn't).

**Comment by JJTech0130** [comment]
Ooh, OK. That makes sense. Should we convert it then? Doesn't look like much effort, I'll even PR it, and it would make it much more obvious how to build it

**Comment by jkcoxson** [comment]
Yeah it should be converted. If you'd do a PR that would be great. Minimuxer also needs a PR.

**Comment by JJTech0130** [comment]
Closing this issue as I made #2 
will make a PR for `minimuxer` in a sec
